# Generated by Django 4.2.16 on 2024-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IaqEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('noise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('illuminance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_status', models.TextField()),
                ('device_status', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'iaq',
            },
        ),
        migrations.CreateModel(
            name='LifeBeingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('datapoint', models.TextField()),
                ('value', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'lifebeing',
            },
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('device_id', models.TextField(primary_key=True, serialize=False)),
                ('offset', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pointer',
            },
        ),
        migrations.AddConstraint(
            model_name='lifebeingevent',
            constraint=models.UniqueConstraint(fields=('device_id', 'datapoint', 'datetime'), name='unique_device_datapoint_datetime'),
        ),
        migrations.AddConstraint(
            model_name='iaqevent',
            constraint=models.UniqueConstraint(fields=('device_id', 'datetime'), name='unique_device_datetime'),
        ),
    ]
