# Generated by Django 4.2.16 on 2024-11-15 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeBeingOnlineStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'life_being_online_status_event',
            },
        ),
        migrations.CreateModel(
            name='LifeBeingPresenceStateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'life_being_presence_state_event',
            },
        ),
        migrations.CreateModel(
            name='LifeBeingSensitivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'life_being_sensitivity_event',
            },
        ),
        migrations.CreateModel(
            name='LifeBeingSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('online_status', models.TextField()),
                ('sensitivity', models.TextField()),
                ('presence_state', models.TextField()),
            ],
            options={
                'db_table': 'life_being_sensor',
                'indexes': [models.Index(fields=['hotel'], name='life_being__hotel_02a7b1_idx'), models.Index(fields=['floor'], name='life_being__floor_d926d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='IaqSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('noise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('illuminance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_status', models.TextField()),
                ('device_status', models.TextField()),
            ],
            options={
                'db_table': 'iaq_sensor',
                'indexes': [models.Index(fields=['hotel'], name='iaq_sensor_hotel_e30e11_idx'), models.Index(fields=['floor'], name='iaq_sensor_floor_abe1f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='IaqEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('hotel', models.TextField()),
                ('floor', models.TextField()),
                ('room', models.TextField()),
                ('device_id', models.TextField()),
                ('noise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pm25', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('illuminance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_status', models.TextField()),
                ('device_status', models.TextField()),
            ],
            options={
                'db_table': 'iaq_event',
                'indexes': [models.Index(fields=['datetime'], name='iaq_event_datetim_db3f2c_idx'), models.Index(fields=['hotel'], name='iaq_event_hotel_50ea4f_idx'), models.Index(fields=['floor'], name='iaq_event_floor_203fb5_idx')],
            },
        ),
    ]
