# Generated by Django 4.2.16 on 2024-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceState',
            fields=[
                ('device_id', models.TextField(primary_key=True, serialize=False)),
                ('presence_state', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presence_state',
            },
        ),
    ]
